import { MetadataRoute } from 'next';

const FLORIDA_COUNTIES = [
  'alachua',
  'baker',
  'bay',
  'bradford',
  'brevard',
  'broward',
  'calhoun',
  'charlotte',
  'citrus',
  'clay',
  'collier',
  'columbia',
  'desoto',
  'dixie',
  'duval',
  'escambia',
  'flagler',
  'franklin',
  'gadsden',
  'gilchrist',
  'glades',
  'gulf',
  'hamilton',
  'hardee',
  'hendry',
  'hernando',
  'highlands',
  'hillsborough',
  'holmes',
  'indian-river',
  'jackson',
  'jefferson',
  'lafayette',
  'lake',
  'lee',
  'leon',
  'levy',
  'liberty',
  'madison',
  'manatee',
  'marion',
  'martin',
  'miami-dade',
  'monroe',
  'nassau',
  'okaloosa',
  'okeechobee',
  'orange',
  'osceola',
  'palm-beach',
  'pasco',
  'pinellas',
  'polk',
  'putnam',
  'saint-johns',
  'saint-lucie',
  'santa-rosa',
  'sarasota',
  'seminole',
  'sumter',
  'suwannee',
  'taylor',
  'union',
  'volusia',
  'wakulla',
  'walton',
  'washington',
];

export default function sitemapCounties(): MetadataRoute.Sitemap {
  const baseUrl = 'https://flbusinesssearch.com';

  return FLORIDA_COUNTIES.flatMap((slug) => [
    {
      url: `${baseUrl}/county/${slug}`,
      lastModified: new Date(),
      changeFrequency: 'daily' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/es/condado/${slug}`,
      lastModified: new Date(),
      changeFrequency: 'daily' as const,
      priority: 0.8,
    },
  ]);
}
